NAME: microservice
LAST DEPLOYED: Thu Nov 10 23:39:40 2022
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
deployment:
  container:
    cpuLimit: 0.5
    cpuRequest: 1
    env:
    - name: ENVIRONMENT
      value: DEBUG
    - name: REDIS_HOST
      value: playlists-db
    - name: REDIS_PORT
      value: "6379"
    image: aimvector/service-mesh
    memoryLimit: 500Mi
    memoryRequest: 500Mi
    name: playlist-api-container
    port: 5000
    tag: playlists-api-1.0.0
  name: playlist-api
  replicas: 1

COMPUTED VALUES:
deployment:
  container:
    cpuLimit: 0.5
    cpuRequest: 1
    env:
    - name: ENVIRONMENT
      value: DEBUG
    - name: REDIS_HOST
      value: playlists-db
    - name: REDIS_PORT
      value: "6379"
    image: aimvector/service-mesh
    memoryLimit: 500Mi
    memoryRequest: 500Mi
    name: playlist-api-container
    port: 5000
    tag: playlists-api-1.0.0
  name: playlist-api
  replicas: 1

HOOKS:
MANIFEST:
---
# Source: microservices-umbrella-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-api
  labels:
    app: playlist-api
spec:
  selector:
    matchLabels:
      app: playlist-api
  replicas: 1
  template:
    metadata:
      labels:
        app: playlist-api
    spec:
      containers:
        - name: playlist-api-container
          image: aimvector/service-meshplaylists-api-1.0.0
          imagePullPolicy : Always
          resources:
            limits:
              memory: 500Mi
              cpu: 0.5
            requests:
              memory: 500Mi
              cpu: 1
          env:
          - name: "ENVIRONMENT"
            value: "DEBUG"
          - name: "REDIS_HOST"
            value: "playlists-db"
          - name: "REDIS_PORT"
            value: "6379"
          ports:
            - containerPort: 5000

