global:
  namespace: microservice
  databasePasswordSecret: redis-secret
deployment:
  name: playlist-api
  replicas: 1
  initContainer:
    name: data-seed
    image: ahmedgrati/data-seed-job
    digest: sha256:f6b070283cc3d3f4d237f45ce8c81c59ac46c6f976eff97b2403ecff9dd554c2
    memoryLimit: 500Mi
    cpuLimit: 1
    memoryRequest: 500Mi
    cpuRequest: .5
  container:
    name: playlist-api-container
    image: aimvector/service-mesh
    digest: sha256:d8ea43bf8dbc045df14a1b6b58c4927f9df3f67ff952fe5edb571cc8f9192674
    memoryLimit: 500Mi
    cpuLimit: 1
    memoryRequest: 500Mi
    cpuRequest: .5
    port: 5000
    healthPath: /

serviceAccount:
  name: playlist-api-sa

service:
  name: playlist-service
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 10010
      targetPort: 10010

configmap:
  name: playlist-env
  data:
    ENVIRONMENT: DEBUG
    REDIS_HOST: playlist-db
    REDIS_PORT: 6379

initConfigMap:
  name: data-seed-env
  data:
    MICROSERVICE: playlist
    REDIS_HOST: playlists-db
    REDIS_PORT: 6379