deployment:
  name: playlist-api
  replicas: 1
  namespace: microservices
  container:
    name: playlist-api-container
    image: aimvector/service-mesh
    digest: sha256:d8ea43bf8dbc045df14a1b6b58c4927f9df3f67ff952fe5edb571cc8f9192674
    memoryLimit: 500Mi
    cpuLimit: 1
    memoryRequest: 500Mi
    cpuRequest: .5
    port: 5000
    healthPath: /
    env:
    - name: "ENVIRONMENT"
      value: "DEBUG"
    - name: "REDIS_HOST"
      value: "playlists-db"
    - name: "REDIS_PORT"
      value: "6379"

serviceAccount:
  name: playlist-api-sa

service:
  name: playlist-service
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 10010
      targetPort: 10010
