global:
  namespace: microservices
  databasePasswordSecret: redis-secret
deployment:
  name: playlist-api
  replicas: 1
  initContainer:
    name: data-seed
    image: ahmedgrati/data-seed-job
    digest: sha256:f6b070283cc3d3f4d237f45ce8c81c59ac46c6f976eff97b2403ecff9dd554c2
    memoryLimit: 500Mi
    cpuLimit: 1
    memoryRequest: 500Mi
    cpuRequest: .5
  container:
    name: playlist-api-container
    image: ahmedgrati/playlist-ms
    digest: sha256:15c77fc920ecf97247da6e2f39cb8697834d64b5dd6aed1dcdb30bda5c63ea42
    memoryLimit: 500Mi
    cpuLimit: 1
    memoryRequest: 500Mi
    cpuRequest: .5
    ports:
      - name: application
        port: 10010
      - name: metrics
        port: 8000
    probe:
      readinessProbe:
        port: 10010
        path: /healthz
      livenessProbe:
        port: 10010
        path: /healthz

serviceAccount:
  name: playlist-api-sa

service:
  name: playlist-service
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 10010
      targetPort: 10010
    - protocol: TCP
      name: metrics
      port: 8000
      targetPort: 8000

configmap:
  name: playlist-env
  data:
    ENVIRONMENT: DEBUG
    REDIS_HOST: playlist-db
    REDIS_PORT: 6379

initConfigMap:
  name: data-seed-env
  data:
    MICROSERVICE: playlist
    REDIS_HOST: playlists-db
    REDIS_PORT: 6379

monitoring:
  enabled: true
  interval: 20s
  targetPort: metrics
  path: /
