apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.container.image }}{{ .Values.deployment.container.tag }}
          imagePullPolicy : Always
          env:
          {{- range .Values.deployment.container.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
